development:
  adapter: postgis
  encoding: unicode
  postgis_extension: true
  schema_search_path: public
  pool: 15
  database: mg_dev
  username: development
  password:
  su_username: christian
  password:

test:
  adapter: postgis
  encoding: unicode
  postgis_extension: true
  schema_search_path: public
  pool: 5
  database: mg_test
  username: christian
  password:
  su_username: christian
  password:

production:
  adapter: postgis
  encoding: unicode
  postgis_extension: true
  schema_search_path: public
  pool: 50
  database: mg_prod
  username: christian
  password: 467802ßnc489672b3v67ßn3984762ß